### ISSUE TITLE
Starting/Ending Angle Doesn't Change Upon Rebuild

### ISSUE THREAD

**Issue by kareem-darwinz** [hasan-hm1/circular_menu#10]
The starting and ending angles of the Circular Menu are not reflected during hot reload or if a rebuild occurs. They're only reflected during a hot restart or rerunning the application. 

I have a case where based on the language chosen the button moves from bottomRight to bottomLeft and so the angles have to be reflected. The button moves to the other side, but the initial angles remain the same even though I have an if condition to change them during the rebuild.

Also, the Widget does not automatically change based on the application RTL/LTR.

**Comment by hasan-hm1** [comment]
Hi @kareem-darwinz 
Thanks for creating this issue  and sorry for the late response,
for the first point (Circular Menu does not reflect on hot reload or rebuild ) please check the updated version , it should reflect now .
for the second point (Widget does not automatically change based on the application RTL/LTR) , I think it does not make a lot of sense to do that , even if the application in RTL you maybe still need the menu to be on the left , so please handle that on your own by manipulating the alignment property like this as an example
`CircularMenu(alignment: isRTL ? Alignment.bottomRight : Alignment.bottomLeft )`
