### ISSUE TITLE
Badge to CircularMenuItem

### ISSUE THREAD

**Issue by Dowlpack** [hasan-hm1/circular_menu#12]
Hello!
Is it possible to add Badge to CircularMenuItem?

**Comment by hasan-hm1** [comment]
Hi @Dowlpack 
Thanks for creating this issue , 
Please check the updated version , now you can easily add a badge to ```CircularMenuItem``` by by setting the property ```enableBadge``` to ```true``` :

```dart
CircularMenuItem(
              enableBadge: true,
            )
```

* customize badge by setting the parameters   ```badgeColor``` , ```badgeLabel``` , ```badgeRadius```
  ```badgeTextColor``` , ```badgeRightOffet``` , ```badgeTopOffet``` , ```badgeBottomOffet``` , ```badgeLeftOffet``` 
  ```badgeTextStyle``` to satisfy  requirements .

```dart
CircularMenuItem(
              enableBadge: true,
              badgeColor: Colors.amber,
              badgeLabel: '3',
              badgeRadius: 15,
              badgeTextColor: Colors.white,
              badgeRightOffet: 0,
              badgeTopOffet: 0,
              onTap: () {
                print('badge on circular menu item');
              },
              icon: Icons.home,
              color: Colors.teal,
            )
```

**Comment by aisummoner** [comment]
Custom Widget for badge ?
