### ISSUE TITLE
CircularMenuItem need to open by default instead of waiting for user to click

### ISSUE THREAD

**Issue by rashmisridar** [hasan-hm1/circular_menu#17]
I want to CircularMenu taped by default so CircularMenuItem will be visible when the user comes to that screen. How to achieve this?

**Comment by hasan-hm1** [comment]
Hi Rashmi,
Please read README.md file , there is a section titled "control animation
anywhere in your code using a key" , by using a GlobalKey you can control
circular menu state as you need.

Regards.

**Comment by rashmisridar** [comment]
@hasan-hm1  Thanks
