### ISSUE TITLE
[Question] Can it be use in ListView?

### ISSUE THREAD

**Issue by jasonlaw** [hasan-hm1/circular_menu#2]
Hi @hasan-hm1 ,

This is a very cool widget!

Can we use this in a list view? 
In my list view, I have ListTile as list item, can I place this menu in the list item?

Thanks in advance.

**Comment by hasan-hm1** [comment]
Hi @jasonlaw

Yes, if you want to place it in a `ListTile ` you can :
1. wrap the `CircularMenu `  with a `Container ` and specify the  `constraints` , then you can place it in  `title`  , `subTitle` , `leading` or `trailling` in the `ListTile`.

**or**

2. wrap the `CircularMenu` with a `Container ` and specify the `constraints` , then use `CircularMenu ` directly as a list item and assign the `ListTile `to `backgroundWidget `in the `CircularMenu`.

I hope this helped you.
