### ISSUE TITLE
Upgrade for Flutter 3.0

### ISSUE THREAD

**Issue by salvatoremiccio** [hasan-hm1/circular_menu#24]
the widget uses inside a stack that no longer has the overflow property starting from Flutter 3.0. Consequently, during the build phase, the Circular Menu does not recognize the Stack and produces an error. I tried to add // near the overflow property in Circular Menu and worked fine.

**Comment by hasan-hm1** [comment]
Thank you for opening this issue.
Upgraded, please check the latest version.
