### ISSUE TITLE
New Requirement: When Click a CircularMenuItem then reduce Circular to its original state

### ISSUE THREAD

**Issue by securexperts** [hasan-hm1/circular_menu#26]
Hello, 
I like very much your circular_menu.
Is it possible to add a boolean trigger in the CircularMenuItem which indicates the CircularMenu Button to close/reduce to its original (not clicked) state?
Many Thanks
Roman

**Comment by ench0** [comment]
I second this. Example: one of the buttons navigate to another page/route, and when I navigate back, the menu is still in 'open' state. Maybe this can be controlled from ```toggleButtonOnPressed``` function? Thanks for great module btw.
