### ISSUE TITLE
Reopen Issue #34: Grey Overlay on circular menu button

### ISSUE THREAD

**Issue by securexperts** [hasan-hm1/circular_menu#36]
Hello, 

I like to reopen my Issue. 

https://github.com/hasan-hm1/circular_menu/issues/34

As of today the new version of Flutter / Dart has been promoted 
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.22.0, on macOS 14.4.1 23E224 darwin-arm64, locale en-GB)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.4)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2023.3)
[✓] IntelliJ IDEA Ultimate Edition (version 2024.1.1)
[✓] Connected device (4 available)
[✓] Network resources

The Plugin has stopped working when promoting it to TestFlight on Apple App Store 

Please Correct this as soon as possible

Thanks

**Comment by hasan-hm1** [comment]
Please refer to #34
