### ISSUE TITLE
[Question] : Icon not visible

### ISSUE THREAD

**Issue by Julietttead** [hasan-hm1/circular_menu#39]
I'm contacting you because I can't get the icons to appear using circularMenuItems.

I've had a good look at the documentation, but I don't understand what I'm doing wrong.

<img width="156" alt="image" src="https://github.com/user-attachments/assets/295eecf9-5ee9-4d3d-a5c6-f3aac7c82aaf">

Thank you in advance for your help,

The version 4.0.0 of cicular_menu id used.

```shell

flutter doctor

┌─────────────────────────────────────────────────────────┐
│ A new version of Flutter is available!                  │
│                                                         │
│ To update to the latest version, run "flutter upgrade". │
└─────────────────────────────────────────────────────────┘
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.22.1, on macOS 14.5 23F79 darwin-arm64, locale fr-FR)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.4)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2024.1)
[✓] IntelliJ IDEA Ultimate Edition (version 2024.1.4)
[✓] VS Code (version 1.91.1)
[✓] Connected device (5 available)
[✓] Network resources

• No issues found!
```

```flutter
CircularMenu(
                        toggleButtonColor: Colors.transparent,
                        alignment: Alignment.topRight,
                        backgroundWidget: const Icon(
                          Icons.menu,
                          color: Colors.white,
                          size: 30,
                        ),
                        items: [
                          CircularMenuItem(
                            iconColor: Colors.white,
                            icon: Icons.leaderboard,
                            iconSize: 20,
                            animatedIcon: null,
                            onTap: () => Navigator.pushNamed(
                              context,
                              Routes.leaderboard,
                              arguments: {
                                'user': widget.user,
                                'company': widget.company
                              },
                            ),
                          ),
                          CircularMenuItem(
                            iconColor: Colors.white,
                            icon: Icons.leaderboard,
                            animatedIcon: null,
                            iconSize: 20,
                            onTap: () => Navigator.pushNamed(
                              context,
                              Routes.settings,
                              arguments: {
                                'user': widget.user,
                                'company': widget.company
                              },
                            ),
                          ),
                          ],
                      )
                      ```

**Comment by hasan-hm1** [comment]
Hi @Julietttead,

Thanks for opening this issue. I see you are using the `backgroundWidget` parameter the wrong way, this parameter represents the actual screen content and it is not related to the circular menu itself. Here is an example of how you can change your code:

CircularMenu(
                        toggleButtonColor: Colors.transparent,
                        alignment: Alignment.topRight,
                        // whatever widget
          backgroundWidget: Center(
            child: const Icon(
              Icons.menu,
              color: Colors.white,
              size: 30,
            ),
          ),
                        items: [
                          CircularMenuItem(
                            iconColor: Colors.white,
                            icon: Icons.leaderboard,
                            iconSize: 20,
                            animatedIcon: null,
                            onTap: () => Navigator.pushNamed(
                              context,
                              Routes.leaderboard,
                              arguments: {
                                'user': widget.user,
                                'company': widget.company
                              },
                            ),
                          ),
                          CircularMenuItem(
                            iconColor: Colors.white,
                            icon: Icons.leaderboard,
                            animatedIcon: null,
                            iconSize: 20,
                            onTap: () => Navigator.pushNamed(
                              context,
                              Routes.settings,
                              arguments: {
                                'user': widget.user,
                                'company': widget.company
                              },
                            ),
                          ),
                          ],
                      )
                      ```

**Comment by Julietttead** [comment]
Hi,

Thanks for your quick reply,

If I understand your explanation correctly, the `backgroundWidet` parameter represents the visible part of the circularManu which is used to trigger the display of the circularMenu.

If that's the case, I've already understood that it's the icons that make up the `items` parameter that I can't display.

Regards

**Comment by hasan-hm1** [comment]
Hi @Julietttead , 

Actually, the `backgroundWidet` parameter represents the screen's main content behind the `CircularMenu`, consider it as a stack there is the screen content, and above this there is the circular menu and its items. I hope it is clear now, also I would like to encourage you to check the example [here](https://pub.dev/packages/circular_menu/example) for a better understanding.

Regards,

**Comment by Julietttead** [comment]
I think I've figured out how it works now, but even using the pub dev example, the icons in `items` don't display.

**Comment by hasan-hm1** [comment]
Could you please share the updated code after you checked the example?

**Comment by Julietttead** [comment]
I've literally copied and pasted the example: I've got the color bubbles but not the icons.
