### ISSUE TITLE
CircularMenuItem onTap not working

### ISSUE THREAD

**Issue by ebena107** [hasan-hm1/circular_menu#7]
I tried out the  package with image selection app.
Both of these approaches were used,
`onTap: () => getImage(ImageSource.gallery)`
`onTap (){getImage(ImageSource.camera)}`
but none trigger getImage method.

**Comment by hasan-hm1** [comment]
Hi @ebena107 
Thanks for opening this issue, 
Circular menu seems to work fine, maybe the issue  is related to something else.
Please provide more info about your widget tree so I can have a closer look at what's happening there.

**Comment by ebena107** [comment]
@hasan-hm1 Thank you for the good work you are doing. The package is beautiful.

However, what I found out is that the problem is with Transform widget, as stated here https://github.com/flutter/flutter/issues/27587 .It doesn't transfer hit area with each menu item, thereby making it impossible to accept onTap or callback.

**Comment by hasan-hm1** [comment]
Hi @ebena107 
Please notice that Circular Menu is designed to be the direct child of a Scaffold 
`Scaffold(body: CircularMenu()`
and the actual page content be assigned to the property backgroundWidget
`Scaffold(body: CircularMenu(
backgroundWidget: PageContent() ,
),
)`
to make sure that the parent is big enough to transfer the tappable area so it can accept a callback.
However, you can use any widget not only a Scaffold but you always have to make sure that the parent is big enough.
